### ISSUE TITLE
UI: Simple fixes - colours, titles, legend

### ISSUE THREAD

**Issue by polly64** [colouring-london/colouring-london#543]
@mz8i  could u possibly have a look at these if they are quick fixes for you? many thanks
- [x] 1. Adjust main category titles ready for Tom redesign - as last comment #490
- [x] 2. Adjust these main also for titles which appear when main category buttons are clicked #541
- [x] 3. Adjust single colour on land use map #541
- [x] 4. Adjust building age colours #525
- [x] 5. ~~Advise/help Dom  adding conservation area boundaries to new listed building map~~ (replaced with CA outline for each building separately) #242
- [x] 5. Remove vacant and derelict from Land use key #529
- [x] 6. Add small colour logo to each map key #236
- [x] 7. Add simple text list info under new main Dynamics title ( for info due to be collected) as 

follows: 
- Under threat of demolition (partial/complete? 
- Demolition permit no. issued, Whole building demolitions for current year, Whole building demolitions since 2000, Pairs of construction and demolition dates for previous buildings built on any part of the site. @polly64 can you confirm the edit I've just made is correct (the bullet pointing)
thank you!

- [x] 8. Change `Size & Form` category to visualise to height as Slack [thread](https://colouringlondon.slack.com/archives/CM3PJTHQV/p1578647874013400) 
- [x] 9. Change `Planning` category to visualise by listed buildings `Listing grade` which links to #538

**Comment by dominijk** [comment]
@polly64 Did you also want to you want to add these two as well?

1. Change `Size & Form` category to visualise to height as Slack [thread](https://colouringlondon.slack.com/archives/CM3PJTHQV/p1578647874013400) 
2. Change `Planning` category to visualise by listed buildings `Listing grade` which links to #538

**Comment by polly64** [comment]
yes please

**Comment by mz8i** [comment]
@polly64 number 2 on the above list links to the same issue as number 3, I think this is a typo - could you please check which issue it was supposed to link?

**Comment by mz8i** [comment]
ticked all items that are already in review.

**Comment by polly64** [comment]
@mz8i shall i keep adding small fixes to this page only?

**Comment by mz8i** [comment]
@polly64 I have created a new label for issues: `small` - please create new issues for each of these tweaks and label them as `small` (using the Labels menu on the right) - then if someone goes to https://github.com/tomalrussell/colouring-london/labels/small they will be able to see all issues labelled as `small`. It will be easier to manage the completion of these tweaks if they are separate.
